baseURL = "https://zhirnoov.github.io"
defaultContentLanguage = "ru"
title = 'Дневник Стартапера'
theme = 'LoveIt'
copyright = "Дневник Стартапера"
enabledRobortsTXT = true
enabledGitInfo = true

 [author]
 name = "Стартапер"
 email = "zhirnoov@yandex.ru"
 link = ""

 [params]
 defaulTheme = "dark"
 title = "Дневник стартапера"
 googleAnalytics = 'G-H1JXTZ0JL5'


[languages]
 [languages.ru.menu]
  [[languages.ru.menu.main]]
   identifier = "posts"
   pre = ""
   post = ""
   name = "Блог"
   url = "/posts/"
   title = ""
   weight = 1
  [[languages.ru.menu.main]]
   identifier = "about"
   pre = ""
   post = ""
   name = "Обо мне"
   url = "/about/"
   title = ""
   weight = 2

 [languages.ru.params]
  description = "Блог о разработке и заработке на мобильных приложениях"

 [languages.ru.params.home.profile]
  enable = true
  gravatarEmail = ""
  title = "Дневник стартапера"
  avatarURL = "https://2ch.hk/dr/src/676641/16845264079270.png"
  subtitle = "Блог о разработке и заработке на мобильных приложениях"
  typeit = true
  social = true
  disclaimer = ""




[params.social]
  [params.social.Github]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "zhirnoov"
    # prefix of your social link
    prefix = "https://github.com/"
    # content hovering on the icon
    title = "Github"
   [params.social.Telegram]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 1
    # your social ID
    id = "@zhirnoov"
    # prefix of your social link
    prefix = "https://t.me/"
    # content hovering on the icon
    title = "Telegram"

[params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Дневник стартапера"
      pre = "<i class='far fa-kiss-wink-heart fa-fw'></i>"
      post = ""
      typeit = false

 [params.verification]
    google = "BoLSGx2zlxdVPzFkwvr9zMlNp4QcCKhhKUVK_dba-e4"

 [params.analytics]
  enable = true
  [params.analytics.google]
      id = "G-H1JXTZ0JL5"
      # whether to anonymize IP
      anonymizeIP = false
  [params.analytics.yandexMetrica]
      id = "93652530"

[params.page.seo]
      # image URL
      # 图片 URL
      images = []
      # Publisher info
      # 出版者信息
      [params.page.seo.publisher]
        name = "Дневник стартапера"
        logoUrl = "/images/avatar.png"


[params.seo]
    # image URL
    # 图片 URL
    image = "/images/avatar.png"
    # thumbnail URL
    # 缩略图 URL
    thumbnailUrl = "/images/avatar.png"